// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbF37RHXqjBvkcemXema7VBUgIv6yqjsk',
    appId: '1:933240164340:web:09429198ce30e95b1773a1',
    messagingSenderId: '933240164340',
    projectId: 'student-freelance-services',
    authDomain: 'student-freelance-services.firebaseapp.com',
    storageBucket: 'student-freelance-services.firebasestorage.app',
    measurementId: 'G-PKJPMN8HGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO8NN_gROT7PRHJLmax1aiJgl18Z0Cy6U',
    appId: '1:933240164340:android:a8ab2785ce234fef1773a1',
    messagingSenderId: '933240164340',
    projectId: 'student-freelance-services',
    storageBucket: 'student-freelance-services.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALRTl-tbnTAwP6qYD3Gatdj4iWHDkS2bk',
    appId: '1:933240164340:ios:cbdbcd205c04db291773a1',
    messagingSenderId: '933240164340',
    projectId: 'student-freelance-services',
    storageBucket: 'student-freelance-services.firebasestorage.app',
    iosBundleId: 'com.example.studentFreelanceServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALRTl-tbnTAwP6qYD3Gatdj4iWHDkS2bk',
    appId: '1:933240164340:ios:cbdbcd205c04db291773a1',
    messagingSenderId: '933240164340',
    projectId: 'student-freelance-services',
    storageBucket: 'student-freelance-services.firebasestorage.app',
    iosBundleId: 'com.example.studentFreelanceServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbF37RHXqjBvkcemXema7VBUgIv6yqjsk',
    appId: '1:933240164340:web:282f44ccd9d58e821773a1',
    messagingSenderId: '933240164340',
    projectId: 'student-freelance-services',
    authDomain: 'student-freelance-services.firebaseapp.com',
    storageBucket: 'student-freelance-services.firebasestorage.app',
    measurementId: 'G-4D2DGVSF90',
  );
}
